plugins {
	id 'java'
	id 'org.springframework.boot' version '3.4.1'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

sourceSets {
	main {
		java {
			srcDir 'src/main/java'
		}
	}

	test {
		java {
			srcDir 'src/test/java'
		}
	}

	testfixture {
		java {
			srcDir 'src/test-fixture/java'
		}
	}

}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
	testImplementation.extendsFrom testfixtureImplementation
}

repositories {
	mavenCentral()
}

dependencies {
	// Spring Boot 스타터 - 웹, 데이터 JPA, 검증
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-validation'

	// Lombok (컴파일 시점에만 필요)
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'

	// MySQL 드라이버 (런타임에 필요)
	runtimeOnly 'com.mysql:mysql-connector-j'

	// Spring Boot 설정 프로세서
	annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'

	// 테스트 관련 의존성
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'io.projectreactor:reactor-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

	// JWT 관련 라이브러리
	implementation 'io.jsonwebtoken:jjwt-api:0.12.5'
	runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.5'
	runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.5'

	// test-fixture Fixture Monkey
	testfixtureImplementation 'com.navercorp.fixturemonkey:fixture-monkey:1.1.11'
	testfixtureImplementation 'com.navercorp.fixturemonkey:fixture-monkey-api:1.1.11'
	testfixtureImplementation 'com.navercorp.fixturemonkey:fixture-monkey-jakarta-validation:1.1.11'

	// test-fixture
	testfixtureImplementation 'org.springframework.boot:spring-boot-starter-test'
	testfixtureImplementation 'io.projectreactor:reactor-test'
	testfixtureImplementation sourceSets.main.output
	testfixtureRuntimeOnly 'org.junit.platform:junit-platform-launcher'

	// test-fixture Fixture Lombok
	testfixtureAnnotationProcessor 'org.projectlombok:lombok'
	testfixtureImplementation 'org.projectlombok:lombok'

	// test-fixture 참조 가능하게
	testImplementation sourceSets.testfixture.output

	// FCM
	implementation 'com.google.firebase:firebase-admin:9.2.0'

	// SSE
	implementation 'org.springframework.boot:spring-boot-starter-data-redis'
	implementation 'org.springframework.boot:spring-boot-starter-webflux'
}

tasks.named('test') {
	useJUnitPlatform()
}
