services:
  # --- 애플리케이션 인프라 서비스 ---
  # 1. course 앱을 위한 DB (3306 포트)
  course_db:
    image: mysql:8.0
    container_name: course_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "course_db"
    ports:
      - "3306:3306"
    volumes:
      - course_mysql_data:/var/lib/mysql
    networks:
      - app_network

  # 2. notification 앱을 위한 DB (3307 포트)
  notification_db:
    image: mysql:8.0
    container_name: notification_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "notification_db"
    ports:
      - "3307:3306"
    volumes:
      - notification_mysql_data:/var/lib/mysql
    networks:
      - app_network

  # 3. Redis
  redis:
    image: redis:latest
    container_name: sse-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network

  # 4. Zookeeper (Kafka 의존성)
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - app_network

#  # 5. Kafka
#  kafka:
#    image: confluentinc/cp-kafka:7.3.2
#    container_name: kafka
#    depends_on:
#      - zookeeper
#    ports:
#      - "9092:9092"
#    environment:
#      KAFKA_BROKER_ID: 1
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
#      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#    networks:
#      - app_network

  # 5. Kafka
  kafka:
    image: confluentinc/cp-kafka:7.3.2
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - app_network



  # --- 모니터링/테스트 서비스 ---
#  prometheus:
#    image: prom/prometheus
#    container_name: prometheus_container
#    ports:
#      - "9090:9090"
#    command:
#      - --web.enable-remote-write-receiver
#      - --enable-feature=native-histograms
#      - --config.file=/etc/prometheus/prometheus.yml
#    networks: # 모든 서비스가 같은 네트워크를 사용하도록 명시
#      - app_network
#
#  grafana:
#    image: grafana/grafana
#    container_name: grafana_container
#    ports:
#      - "3000:3000"
#    volumes:
#      - ./grafana-provisioning:/etc/grafana/provisioning
#      - ./grafana-dashboard:/dashboard
#    depends_on:
#      - prometheus
#    networks:
#      - app_network
#
#  k6:
#    image: grafana/k6
#    container_name: k6_container
#    volumes:
#      - ./playground/k6-scripts:/scripts
#    command: run -o experimental-prometheus-rw /scripts/special-lecture-enrollment-concurrent-immediately-test.js
#    environment:
#      - K6_PROMETHEUS_RW_SERVER_URL=http://prometheus:9090/api/v1/write
#      - K6_PROMETHEUS_RW_TREND_AS_NATIVE_HISTOGRAM=true
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
#    depends_on:
#      - prometheus
#    networks:
#      - app_network



networks:
  app_network:
    driver: bridge

volumes:
  course_mysql_data:
  notification_mysql_data:
  redis_data:
