-- V1 baseline: 운영 `ssa` 스키마 DDL (ADR-0003 Stage 0, ADR-0006 결정 6)
--
-- 출처: 2026-10-02 운영 DB 조회 (information_schema.columns, pg_constraint, pg_indexes).
-- 운영 스키마는 Hibernate ddl-auto:update가 엔티티에서 만들었고, 이 파일은 그 결과를 그대로 옮긴 정본이다.
-- 제약 이름(fk..., uk...)도 운영과 같게 둔다.
--
-- 실행 여부:
--   · 운영: flyway_schema_history의 V1이 BASELINE(checksum null)이라 이 파일은 실행되지 않는다.
--     (baseline-on-migrate=true, baseline-version=1. Flyway는 baseline 이하 버전을 적용하지도,
--      체크섬을 검증하지도 않는다.)
--   · 새 환경(빈 스키마): 이 파일이 실행되어 운영과 같은 스키마를 만든다. V2, V3는 IF EXISTS 조건부라 no-op.
--
-- 운영에만 남아 엔티티에는 없는 컬럼(pending_lecture_enrollment의 created/updated/deleted_date 등)도
-- 운영과 같게 포함한다. ddl-auto:validate는 엔티티에 없는 여분 컬럼을 허용한다.
-- 새 DDL은 반드시 V4 이상으로 추가한다.

-- 일정 (JOINED 상속 루트)
CREATE TABLE schedule (
    type         varchar(31)  NOT NULL,
    schedule_id  bigint GENERATED BY DEFAULT AS IDENTITY,
    created_date timestamp(6),
    updated_date timestamp(6),
    deleted_date timestamp(6),
    end_time     timestamp(6) NOT NULL,
    memo         varchar(255),
    start_time   timestamp(6) NOT NULL,
    title        varchar(255) NOT NULL,
    version      bigint       NOT NULL,
    CONSTRAINT schedule_pkey PRIMARY KEY (schedule_id)
);

-- 회원 (JOINED 상속 루트)
CREATE TABLE member (
    role         varchar(31)  NOT NULL,
    member_id    bigint GENERATED BY DEFAULT AS IDENTITY,
    created_date timestamp(6),
    updated_date timestamp(6),
    deleted_date timestamp(6),
    age          integer      NOT NULL,
    name         varchar(255) NOT NULL,
    password     varchar(255) NOT NULL,
    phone_number varchar(255) NOT NULL,
    username     varchar(50)  NOT NULL,
    CONSTRAINT member_pkey PRIMARY KEY (member_id),
    CONSTRAINT ukgc3jmn7c2abyo3wf6syln5t2i UNIQUE (username)
);

CREATE TABLE student (
    school    varchar(255) NOT NULL,
    member_id bigint       NOT NULL,
    CONSTRAINT student_pkey PRIMARY KEY (member_id),
    CONSTRAINT fk445al81r3umky7e7wlkou8up1 FOREIGN KEY (member_id) REFERENCES member (member_id)
);

CREATE TABLE tutor (
    career_period integer NOT NULL,
    member_id     bigint  NOT NULL,
    CONSTRAINT tutor_pkey PRIMARY KEY (member_id),
    CONSTRAINT fkloqi2om3b862k6j3xljsmcelp FOREIGN KEY (member_id) REFERENCES member (member_id)
);

CREATE TABLE parent (
    children_number integer NOT NULL,
    member_id       bigint  NOT NULL,
    CONSTRAINT parent_pkey PRIMARY KEY (member_id),
    CONSTRAINT fkl7ix3cw9godbli7i98cp4v4w5 FOREIGN KEY (member_id) REFERENCES member (member_id)
);

-- 일정 하위 타입
CREATE TABLE lecture (
    capacity       integer NOT NULL,
    enrolled_count integer NOT NULL,
    schedule_id    bigint  NOT NULL,
    tutor_id       bigint,
    CONSTRAINT lecture_pkey PRIMARY KEY (schedule_id),
    CONSTRAINT fkb7tq4t24sog9tokbm86vr0d2y FOREIGN KEY (schedule_id) REFERENCES schedule (schedule_id),
    CONSTRAINT fkgfdch4u5404i0dqcda15pc8xd FOREIGN KEY (tutor_id) REFERENCES tutor (member_id)
);

CREATE TABLE special_lecture (
    capacity    integer NOT NULL,
    schedule_id bigint  NOT NULL,
    tutor_id    bigint,
    CONSTRAINT special_lecture_pkey PRIMARY KEY (schedule_id),
    CONSTRAINT fk3har3lub3l9kcd924agrmmhoj FOREIGN KEY (schedule_id) REFERENCES schedule (schedule_id),
    CONSTRAINT fkoefuc9alhy7hrt8o8tyy8w814 FOREIGN KEY (tutor_id) REFERENCES tutor (member_id)
);

CREATE TABLE consultation (
    schedule_id bigint NOT NULL,
    tutor_id    bigint,
    CONSTRAINT consultation_pkey PRIMARY KEY (schedule_id),
    CONSTRAINT fk72j5g1bgdlmk0glgloxr76kc9 FOREIGN KEY (schedule_id) REFERENCES schedule (schedule_id),
    CONSTRAINT fk4wo102qwu02v3bqihpo4x6o03 FOREIGN KEY (tutor_id) REFERENCES tutor (member_id)
);

CREATE TABLE consultation_attendee (
    id              bigint GENERATED BY DEFAULT AS IDENTITY,
    consultation_id bigint,
    member_id       bigint,
    CONSTRAINT consultation_attendee_pkey PRIMARY KEY (id),
    CONSTRAINT fk42lx53ebnbyk3kacsg22dfd0t FOREIGN KEY (consultation_id) REFERENCES consultation (schedule_id),
    CONSTRAINT fk8osk1ol2oml3k0i0pcpjxywy1 FOREIGN KEY (member_id) REFERENCES parent (member_id)
);

-- 수강
CREATE TABLE lecture_enrollment (
    id         bigint GENERATED BY DEFAULT AS IDENTITY,
    lecture_id bigint NOT NULL,
    student_id bigint NOT NULL,
    CONSTRAINT lecture_enrollment_pkey PRIMARY KEY (id),
    CONSTRAINT uk_lecture_student UNIQUE (lecture_id, student_id),
    CONSTRAINT fk3p6tgpd0ceif2xskvn6b5b16r FOREIGN KEY (lecture_id) REFERENCES lecture (schedule_id),
    CONSTRAINT fks9cxoj92taam56hl98em4smgl FOREIGN KEY (student_id) REFERENCES student (member_id)
);

-- 운영에는 FK가 없다 (논리 참조). 소프트 삭제 시절 컬럼이 남아 있다.
CREATE TABLE pending_lecture_enrollment (
    id           bigint GENERATED BY DEFAULT AS IDENTITY,
    created_date timestamp(6),
    updated_date timestamp(6),
    deleted_date timestamp(6),
    lecture_id   bigint,
    permitted    boolean NOT NULL,
    student_id   bigint,
    CONSTRAINT pending_lecture_enrollment_pkey PRIMARY KEY (id),
    CONSTRAINT uk_pending_lecture_student UNIQUE (lecture_id, student_id)
);

CREATE TABLE special_lecture_enrollment (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY,
    special_lecture_id bigint NOT NULL,
    student_id         bigint NOT NULL,
    CONSTRAINT special_lecture_enrollment_pkey PRIMARY KEY (id),
    CONSTRAINT uk_special_lecture_student UNIQUE (special_lecture_id, student_id),
    CONSTRAINT fksiofe06mg47yvdwcprlr0j0kw FOREIGN KEY (special_lecture_id) REFERENCES special_lecture (schedule_id),
    CONSTRAINT fk5qyogd6958vipd5okq7w6swc7 FOREIGN KEY (student_id) REFERENCES student (member_id)
);

-- 알림
CREATE TABLE fcm_token (
    fcm_id    bigint GENERATED BY DEFAULT AS IDENTITY,
    fcm_token varchar(255),
    member_id bigint,
    CONSTRAINT fcm_token_pkey PRIMARY KEY (fcm_id)
);

CREATE TABLE failed_notification (
    id           bigint GENERATED BY DEFAULT AS IDENTITY,
    created_date timestamp(6),
    updated_date timestamp(6),
    deleted_date timestamp(6),
    body         varchar(255),
    fail_reason  varchar(255),
    retry_count  integer NOT NULL,
    sender_id    bigint,
    target_id    bigint,
    title        varchar(255),
    type         varchar(255),
    uuid         varchar(255),
    CONSTRAINT failed_notification_pkey PRIMARY KEY (id),
    CONSTRAINT failed_notification_type_check CHECK (type IN ('SSE', 'FCM'))
);

-- 공유 인프라: 아웃박스, 멱등, dead letter (ADR-0003 #9)
CREATE TABLE domain_event (
    event_type       varchar(31)  NOT NULL,
    id               bigint GENERATED BY DEFAULT AS IDENTITY,
    created_date     timestamp(6),
    updated_date     timestamp(6),
    deleted_date     timestamp(6),
    fail_reason      varchar(255),
    retry_count      integer      NOT NULL,
    status           varchar(255),
    target_domain_id bigint       NOT NULL,
    uuid             varchar(255),
    lecture_title    varchar(255),
    student_id       bigint,
    tutor_id         bigint,
    updated_details  varchar(255),
    CONSTRAINT domain_event_pkey PRIMARY KEY (id),
    CONSTRAINT uk3eej3soxtp6ae3km43ha6ecad UNIQUE (uuid),
    CONSTRAINT domain_event_status_check CHECK (status IN ('INIT', 'PRODUCE_SUCCESS', 'PRODUCE_FAIL', 'DEAD'))
);

CREATE TABLE kafka_message_consume_history (
    id           bigint GENERATED BY DEFAULT AS IDENTITY,
    created_date timestamp(6),
    updated_date timestamp(6),
    deleted_date timestamp(6),
    topic        varchar(255) NOT NULL,
    uuid         varchar(255),
    CONSTRAINT kafka_message_consume_history_pkey PRIMARY KEY (id),
    CONSTRAINT ukkmhjj211uvfy898vxjfy80g0o UNIQUE (uuid)
);

CREATE TABLE dead_letter (
    id           bigint GENERATED BY DEFAULT AS IDENTITY,
    created_date timestamp(6),
    updated_date timestamp(6),
    deleted_date timestamp(6),
    fail_reason  varchar(255),
    recovered    boolean      NOT NULL,
    uuid         varchar(255) NOT NULL,
    CONSTRAINT dead_letter_pkey PRIMARY KEY (id)
);
