-- V4: 통합 신원 account, account_link 생성과 SSA 회원 백필 (ADR-0006 P1, 결정 1과 2)
--
-- 1. account_id_seq: SSA 회원과 GeekChat 전용 사용자가 같은 id 공간을 쓰도록 하나의 시퀀스로 모은다.
--    member.member_id의 identity를 걷어 내고 기본값을 이 시퀀스로 바꾼다. 그래야 V5에서 GeekChat 전용
--    사용자에게 준 id를 이후 SSA 가입자가 다시 받는 충돌이 생기지 않는다.
--    시작값은 max(member_id)와 기존 identity 시퀀스 값 중 큰 쪽 + 1이다(삭제된 id 재사용 방지).
-- 2. account: SSA 회원은 account.id = member_id로 승계한다. 소프트 삭제된 회원은 탈퇴(익명화) 상태로 둔다.
--    비밀번호 해시는 P1에서 옮기지 않는다. P1에는 account를 읽는 코드가 없고, 해시를 두 곳에 두면
--    로그인 때 bcrypt 승급(ADR-0004)이 member에만 반영돼 사본이 낡는다. 자격 이관은 P2에서 한다.
-- 3. account_link: GeekChat 쪽과 같은 username을 가진 계정의 연결 대기(PENDING)와 확정(CONFIRMED). 채우는 건 V5.
--
-- 운영 적용 전 확인 (ADR-0006 P1 런북): 소문자화한 username이 20자를 넘거나 서로 겹치면 이 마이그레이션은
-- 실패하고 트랜잭션 전체가 롤백된다(조용히 잘리지 않는다).
-- 되돌리기: ADR-0006 "P1 롤백" 절의 SQL. 여기에 V 번호로 넣으면 자동 실행되므로 문서에만 둔다.

CREATE SEQUENCE account_id_seq;

DO $$
DECLARE
    identity_seq text := pg_get_serial_sequence('member', 'member_id');
    identity_last bigint := 0;
    next_id bigint;
BEGIN
    IF identity_seq IS NOT NULL THEN
        EXECUTE format('SELECT last_value FROM %s', identity_seq) INTO identity_last;
    END IF;
    SELECT GREATEST(COALESCE(MAX(member_id), 0), identity_last) + 1 INTO next_id FROM member;
    PERFORM setval('account_id_seq', next_id, false);
END $$;

ALTER TABLE member ALTER COLUMN member_id DROP IDENTITY IF EXISTS;
ALTER TABLE member ALTER COLUMN member_id SET DEFAULT nextval('account_id_seq');

CREATE TABLE account (
    id            bigint       NOT NULL DEFAULT nextval('account_id_seq'),
    external_uuid varchar(36),
    username      varchar(20),
    password_hash varchar(255),
    email         varchar(255),
    status        varchar(20)  NOT NULL,
    created_at    timestamp(6) with time zone NOT NULL,
    updated_at    timestamp(6) with time zone NOT NULL,
    withdrawn_at  timestamp(6) with time zone,
    CONSTRAINT account_pkey PRIMARY KEY (id),
    CONSTRAINT uk_account_external_uuid UNIQUE (external_uuid),
    CONSTRAINT uk_account_username UNIQUE (username),
    CONSTRAINT account_status_check CHECK (status IN ('ACTIVE', 'WITHDRAWN')),
    -- 소문자 정규화 불변식 (Username 값 객체와 같은 규칙의 일부)
    CONSTRAINT account_username_lower_check CHECK (username = lower(username)),
    -- 탈퇴는 익명화: 탈퇴 계정은 식별 정보를 갖지 않는다 (결정 3)
    CONSTRAINT account_withdrawn_anonymized_check CHECK (
        status <> 'WITHDRAWN' OR (username IS NULL AND email IS NULL AND password_hash IS NULL AND withdrawn_at IS NOT NULL))
);

CREATE TABLE account_link (
    id            bigint GENERATED BY DEFAULT AS IDENTITY,
    account_id    bigint       NOT NULL,
    external_uuid varchar(36)  NOT NULL,
    status        varchar(20)  NOT NULL,
    created_at    timestamp(6) with time zone NOT NULL,
    confirmed_at  timestamp(6) with time zone,
    CONSTRAINT account_link_pkey PRIMARY KEY (id),
    CONSTRAINT uk_account_link_external_uuid UNIQUE (external_uuid),
    CONSTRAINT fk_account_link_account FOREIGN KEY (account_id) REFERENCES account (id),
    CONSTRAINT account_link_status_check CHECK (status IN ('PENDING', 'CONFIRMED'))
);

-- SSA 회원 백필. 시각 컬럼이 비어 있는 옛 행은 마이그레이션 시각으로 채운다.
INSERT INTO account (id, username, status, created_at, updated_at, withdrawn_at)
SELECT m.member_id,
       CASE WHEN m.deleted_date IS NULL THEN lower(m.username) END,
       CASE WHEN m.deleted_date IS NULL THEN 'ACTIVE' ELSE 'WITHDRAWN' END,
       COALESCE(m.created_date, now()),
       COALESCE(m.updated_date, m.created_date, now()),
       m.deleted_date
FROM member m
ON CONFLICT (id) DO NOTHING;
