spring:
  application:
    name: SimpleScheduleAppBack

  datasource:
    url: jdbc:mysql://localhost:3306/simple_schedule_app
    username: root
    password: maketws1!
    driver-class-name: com.mysql.cj.jdbc.Driver
