server:
  port: 8081

spring:
  application:
    name: notification

  profiles:
    group:
      local:
        common-local
    active: local

  datasource:
    url: jdbc:mysql://localhost:3307/notification_db
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
    open-in-view: false # SSE Emitter 로 인한 Connection 고갈 방지 설정

  sql:
    init:
      mode: always

  kafka:
    consumer:
      group-id: "ssa-notification-server-group"

logging:
  level:
    org:
      springframework:
        data:
          jpa: DEBUG
      hibernate: DEBUG

fcm:
  key:
    json: ssa-fcm-firebase-adminsdk-fbsvc-cabee70300.json
    url: https://www.googleapis.com/auth/firebase.messaging

cors:
  allowed-origins: http://localhost:3000

redis:
  host: localhost
  port: 6379

client:
  course-server-internal-url: "http://localhost:8080/internal"
