plugins {
	id 'java'
	id 'java-library'
	id 'java-test-fixtures'
	id 'org.springframework.boot' version "3.4.3"
	id 'io.spring.dependency-management' version "1.1.7"
}

group = "com.example"
version = "0.0.1-SNAPSHOT"

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

dependencies {
	// 공통
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-validation'

	// JWT
	implementation 'io.jsonwebtoken:jjwt-api:0.12.5'
	runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.5'
	runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.5'

	// Lombok
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'

	// 테스트
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'io.projectreactor:reactor-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

	// Fixture Monkey
	testFixturesImplementation 'com.navercorp.fixturemonkey:fixture-monkey:1.1.11'
	testFixturesImplementation 'com.navercorp.fixturemonkey:fixture-monkey-api:1.1.11'
	testFixturesImplementation 'com.navercorp.fixturemonkey:fixture-monkey-jakarta-validation:1.1.11'

	// test-fixture 설정
	testFixturesImplementation 'org.springframework.boot:spring-boot-starter-test'
	testFixturesRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	testFixturesAnnotationProcessor 'org.projectlombok:lombok'
	testFixturesImplementation 'org.projectlombok:lombok'

	// Kafka client
	implementation 'org.apache.kafka:kafka-clients:3.7.1'

	// Kafka
	implementation 'org.springframework.kafka:spring-kafka'
	testFixturesImplementation 'org.springframework.kafka:spring-kafka-test'
}

tasks.named('bootJar') {
	enabled = false
}

tasks.named('jar') {
	enabled = true
}
