server:
  port: 8080

spring:
  application:
    name: course

  profiles:
    group:
      local:
        common-local
    active: local

  datasource:
    url: jdbc:mysql://localhost:3306/course_db
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      maximum-pool-size: 21
      connection-timeout: 30000 # 30초
      max-lifetime: 600000      # 600000 (10분)

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: never

  kafka:
    consumer:
      group-id: "ssa-course-server-group"

  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org:
      springframework:
        data:
          jpa: DEBUG
      hibernate: DEBUG

cors:
  allowed-origins: http://localhost:3000
