package com.example.simplescheduleapp.common.kafka.topic;

public class KafkaTopics {

    public static final String LECTURE_UPDATED_TOPIC = "LECTURE_UPDATED_TOPIC";
    public static final String REQUEST_LECTURE_ENROLLMENT_TOPIC = "REQUEST_LECTURE_ENROLLMENT_TOPIC";
    public static final String ACCEPT_LECTURE_ENROLLMENT_TOPIC = "ACCEPT_LECTURE_ENROLLMENT_TOPIC";
    public static final String REJECT_LECTURE_ENROLLMENT_TOPIC = "REJECT_LECTURE_ENROLLMENT_TOPIC";
    public static final String CANCEL_LECTURE_ENROLLMENT_TOPIC = "CANCEL_LECTURE_ENROLLMENT_TOPIC";
    public static final String ENROLL_SPECIAL_LECTURE_ENROLLMENT_SUCCESS_TOPIC = "ENROLL_SPECIAL_LECTURE_ENROLLMENT_SUCCESS_TOPIC";
}
