plugins {
	id 'java'
	id 'java-library'
	id 'org.springframework.boot' version "3.4.3"
	id 'io.spring.dependency-management' version "1.1.7"
}

group = "com.example"
version = "0.0.1-SNAPSHOT"

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

dependencies {
	// =====
	// Common 모듈 의존
	implementation project(':common')

	// Common의 테스트 픽스처(Fixture Monkey 등) 사용
	testImplementation(testFixtures(project(':common')))

	// Redisson
	implementation 'org.redisson:redisson-spring-boot-starter:3.29.0'

	// DB 드라이버
	runtimeOnly 'com.mysql:mysql-connector-j'
	runtimeOnly 'com.h2database:h2'

	// Configuration Processor (Lombok과 별개로 설정 파일 자동완성용)
	annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'
	// =====



//	implementation project(':common')
//	testImplementation(testFixtures(project(':common')))
//
//	implementation 'org.springframework.boot:spring-boot-starter-web'
//	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
//	implementation 'org.springframework.boot:spring-boot-starter-validation'
//
//	compileOnly 'org.projectlombok:lombok'
//	annotationProcessor 'org.projectlombok:lombok'
//
//	testImplementation 'org.springframework.boot:spring-boot-starter-test'
//	testImplementation 'io.projectreactor:reactor-test'
//	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
//
//	// redisson
//	implementation 'org.redisson:redisson-spring-boot-starter:3.29.0'
//
//	runtimeOnly 'com.mysql:mysql-connector-j'
//	annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'
//
//	implementation 'org.springframework.kafka:spring-kafka'
//	testImplementation 'org.springframework.kafka:spring-kafka-test'
//
//	testImplementation 'com.h2database:h2'
}
