plugins {
	id 'java'
	id 'java-library'
	id 'org.springframework.boot' version "3.4.3"
	id 'io.spring.dependency-management' version "1.1.7"
}

group = "com.example"
version = "0.0.1-SNAPSHOT"

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

dependencies {
	// Common 모듈 의존
	implementation project(':common')
	testImplementation(testFixtures(project(':common')))

	// Redisson
	implementation 'org.redisson:redisson-spring-boot-starter:3.29.0'

	// Actuator
	implementation 'org.springframework.boot:spring-boot-starter-actuator'

	// DB 드라이버
	runtimeOnly 'com.mysql:mysql-connector-j'
	runtimeOnly 'com.h2database:h2'

	// Configuration Processor (Lombok과 별개로 설정 파일 자동완성용)
	annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'
}
